sourcefile=exported # File with the output of export.sh
maildir=/var/vmail/vmail1
quota=100 # 100 MB
maildir_style=hashed # hashed/normal
mysql_username=root
mysql_password=
mysql_database=vmail
maildirs_sourcefile=maildirs # File with the output of maildirs.sh
maildirs_sourceserver=root@sourceserver
